language: cpp
dist: xenial
sudo: true
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository http://packages.cor-lab.de/ubuntu/
  - wget -q http://packages.cor-lab.de/keys/cor-lab.asc -O- | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install spread cmake g++ git libboost-date-time-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libboost-signals-dev libboost-system-dev libboost-thread-dev libprotobuf-dev protobuf-compiler lcov gcovr make unzip wget
before_script:
  - mkdir upstream
  - cd upstream
  - wget "https://dl.bintray.com/open-rsx/travis-artifacts/rsc-${CC}-master.tar.gz"
  - "tar -xzf rsc-*.tar.gz"
  - wget "https://dl.bintray.com/open-rsx/travis-artifacts/rsb-cpp-${CC}-master.tar.gz"
  - "tar -xzf rsb-cpp-*.tar.gz"
  - cd ..
script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/rsb-spread-cpp -DCMAKE_PREFIX_PATH="$(pwd)/../upstream/rsc;$(pwd)/../upstream/rsb-cpp" -DCMAKE_BUILD_TYPE=coverage ..
  - make -j3
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - &deploy-stage
      compiler: clang
      stage: archive
      script:
        - mkdir -p build && cd build
        - cmake -DCMAKE_INSTALL_PREFIX=/rsb-spread-cpp -DCMAKE_PREFIX_PATH="$(pwd)/../upstream/rsc;$(pwd)/../upstream/rsb-cpp" ..
        - make -j3
        - make DESTDIR=install_dir install
        - tar -C install_dir -czf "rsb-spread-cpp-${CC}.tar.gz" rsb-spread-cpp
        - |
          cat << EOF > bintray.json
          {
            "package": {
              "name": "rsb-spread-cpp",
              "repo": "travis-artifacts",
              "subject": "open-rsx",
              "desc": "Travis artifact for branch ${TRAVIS_BRANCH}",
              "vcs_url": "https://github.com/open-rsx/rsb-spread-cpp.git",
              "licenses": ["LGPL-3.0"]
            },

            "version": {
              "name": "travis-${TRAVIS_BRANCH}",
              "vcs_tag": "${TRAVIS_BRANCH}"
            },

            "files": [
              {
                "includePattern": "\./(rsb-spread-cpp-.*).tar.gz",
                "uploadPattern": "\$1-${TRAVIS_BRANCH}.tar.gz",
                "matrixParams": {
                  "override": 1
                }
              }
            ],
            "publish": true
          }
          EOF
      after_success:
      deploy:
        provider: bintray
        file: "bintray.json"
        user: "languitar"
        key: '${BINTRAY_KEY}'
        skip_cleanup: true
        on:
          repo: open-rsx/rsb-spread-cpp
          all_branches: true
    - <<: *deploy-stage
      compiler: gcc
